#include <stdio.h>

int main()
{
    int T, N, D, i, j, k, l, m, apple_days, orange_days, mango_days, lemon_days, coconut_days;
    int max_income = 0, income, apple_qty, orange_qty, mango_qty, lemon_qty, coconut_qty;
    scanf("%d", &T); // Read the number of test cases

    for(i=1; i<=T; i++)
    {
        scanf("%d %d", &N, &D); // Read the number of trees and number of days
        max_income = 0; // Reset max_income for each test case
        for(j=1; j<=D; j++) // Loop through each day
        {
            apple_days = j % 10; // Calculate the number of days since the last apple harvest
            orange_days = j % 6; // Calculate the number of days since the last orange harvest
            mango_days = j % 15; // Calculate the number of days since the last mango harvest
            lemon_days = j % 5; // Calculate the number of days since the last lemon harvest
            coconut_days = j % 15; // Calculate the number of days since the last coconut harvest

            // Calculate the quantity of each fruit harvested on this day
            apple_qty = (apple_days == 0) ? (400/N) : 0;
            orange_qty = (orange_days == 0) ? (280/N) : 0;
            mango_qty = (mango_days == 0) ? (2200/N) : 0;
            lemon_qty = (lemon_days == 0) ? (1500/N) : 0;
            coconut_qty = (coconut_days == 0) ? (75/N) : 0;

            // Calculate the income generated by selling the harvested fruits
            income = (apple_qty/5)*150 + (orange_qty/7)*250 + (mango_qty/8)*100 + (lemon_qty/10)*50 + (coconut_qty/15)*1600;

            if(income > max_income) // Check if this is the maximum income so far
                max_income = income;
        }

        printf("Case #%d: %d\n", i, max_income); // Print the output for this test case
    }

    return 0;
}